### ISSUE TITLE
German data source

### ISSUE THREAD

**Issue by carstendirks** [73cirdan/MMM-rainfc#14]
Hi,
I am using your module for quite a while - works great. Unfortunately over the past weeks & months less and less data was available from the Dutch radar. I live close to Frankfurt and that of course is too far away. I therefore used the data provided by the DWD (Deutscher Wetterdienst).
For that I had to change the module quite a bit in regards to getting the data & calculating the data since DWD has a different format and data type.
I am not sure how to make this optional since it is almost a new code stream. Do you want to try to build this into your module or should I clone your module and change it to make it compliant with the German data source?
Best,
Carsten

**Comment by lavolp3** [comment]
@carstendirks Does DWD provide 5-minute rain forecasts? I really didn't know. Can you hint me to the source? I'd be happy to use that as well in my module MMM-Buienalarm since I'm also German :-)

**Comment by carstendirks** [comment]
Sure: https://morgenwirdes.de/api/v2/rjson.php?plz=61381 (it is an API on top of the DWD data), instead of the PLZ you can also use geo location data (see https://morgenwirdes.de/api/)

**Comment by carstendirks** [comment]
This was the one code change I did in rainfc.js:

`            // parse phrases
		var lines = data.split("},{");
		var numLines = lines.length-1; // always a empty line at the end
		Log.info(this.name + ": MaxLines: " + numLines);
		for (i = 0; i < numLines; i++) {
  			var line = lines[i];
			//Log.info(this.name + ":Line: " + line);
			var pipeIndex = line.indexOf(',');
			var fields = line.split(",");
			//Log.info(this.name + "Feld 1: " + fields[0]);
			//Log.info(this.name + "Feld 2: " + fields[1]);
			//Log.info(this.name + "Feld 3: " + fields[2]);
			//Log.info(" ");
			strTime = fields[0].substring((fields[0].indexOf(":")+2),(fields[0].length-1))
			Log.info(this.name + " :Zeit: "+ strTime);
			strdBZ = fields[2].substring((fields[2].indexOf(":")+2),(fields[2].length-1))
			Log.info(this.name + " :dBZ: "+ strdBZ);
			Log.info(" ");
			r = parseInt(strdBZ); //parseInt(line.substring(0, pipeIndex));
			if (r <= 0) {
				r = 0;
			}
			else {
				r = r / 10;
				r = Math.pow(10,r);
				r = r / 256;
				r = Math.pow(r, (1/1.42));
				r = (Math.round(r*100))/100;
			}
			
			t = strTime; //line.substring(pipeIndex+1, line.length);
			Log.info(this.name + " :Rain: "+ r);
			Log.info(" ");

 			// calculate totalrain (if no rain expected don't show graph)
			this.totalrain +=  r;

			// determine maximum amount of rain
			if (r > this.maxrain) {
				this.maxrain = r;
				Log.info("r = " + r);
			}
			
			this.rains.push( r*10 ); // r/2.55
			this.times.push( t );
		}

		// calculate rain in mm/h and round to 2 digits
		if (this.maxrain > 0) {
			// There is a formula to calculate mm/h from dBZ value for rain
			// https://www.dwd.de/DE/leistungen/radarniederschlag/rn_info/download_niederschlagsbestimmung.pdf?__blob=publicationFile&v=4
			/*this.maxrain = this.maxrain / 10;
			this.maxrain = Math.pow(10,this.maxrain);
			this.maxrain = this.maxrain / 256;
			this.maxrain = Math.pow(this.maxrain, (1/1.42));
			this.maxrain = (Math.round(this.maxrain*100))/100;*/
			Log.info(this.name + " :maxrain = " + this.maxrain);	
		}`

**Comment by carstendirks** [comment]
And of course the change to the URL in node_helper.js

**Comment by carstendirks** [comment]
Not sure why the above code won't format correctly. It is one code stream (not yet cleaned)

**Comment by lavolp3** [comment]
Great! Thanks for that! I'll implement that in my module and will get back to you.
