### ISSUE TITLE
'Geen regen tot 11:15' no update/graph.

### ISSUE THREAD

**Issue by GuySwarte** [73cirdan/MMM-rainfc#19]
Hi Cirdan,

After git clone:

pi@raspberrypi:~/MagicMirror/modules/MMM-rainfc $ npm install

added 8 packages, and audited 9 packages in 7s

1 package is looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
pi@raspberrypi:~/MagicMirror/modules/MMM-rainfc $ npm audit
# npm audit report

axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix --force`
Will install axios@1.6.2, which is a breaking change
node_modules/axios

1 moderate severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force
pi@raspberrypi:~/MagicMirror/modules/MMM-rainfc $ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating axios to 1.6.2, which is a SemVer major change.

added 1 package, changed 1 package, and audited 10 packages in 6s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
pi@raspberrypi:~/MagicMirror/modules/MMM-rainfc $

I did use npm audit fix --force to see if the the graph is shown. unfortunaly it didn't.

- RaspberryPI 3B
- Latest Rasbian OS
- Latest version of MagicMirror.

It worked juest fine for years... 
Is the problem known and do you have any solution?

Best regards,
Guy.

**Comment by mjmare** [comment]
Same here

**Comment by 73cirdan** [comment]
I've written a question at the buienradar site

**Comment by GuySwarte** [comment]
Thanks a lot! In the meanwhile I will see what I can do to fix the issue.

**Comment by HaViGit** [comment]
Unfortunately it doesn't work for me anymore, same problem. Hopefully a solution soon.

**Comment by GuySwarte** [comment]
Problem solved. Buienradar is working correct again.

Best to you all!,
Guy.

**Comment by 73cirdan** [comment]
Nice. Did the module automaticaly pick up the recovered service at buienradar, or did you need a restart of the magic mirror?

**Comment by HaViGit** [comment]
That's right, I didn't have to do anything :-)

**Comment by MJM-Debug** [comment]
Here too! Thanks for the prompt action.

**Comment by GuySwarte** [comment]
It was not the fault of the module but of Buienradar itself.

MagicMirror hangs in our living room, so we immediately noticed it when the data came back. Don't have to do anything. Although I of course doubt everything, I deleted the MMM-rainfc and reinstalled it... So a vain effort.

Fortunately everything works again! My compliments to the creator 73cirdan because it is really a great module.
