### ISSUE TITLE
Colors of Title and text (e.g. no rain expected) not changeable for a MMM-rainfc user

### ISSUE THREAD

**Issue by martinkooij** [73cirdan/MMM-rainfc#2]
Can you give an option or point me to a .css where I can change the color and style of the text. In my mirror "no rain expected is too small and too vague. I am not very well versen in .css so I might need some help here. In Dutch is OK.

**Comment by lavolp3** [comment]
There is a .css file in the module which should overwrite the MM general css.
You can try to find the correct designation from the general css in MM or from the MM readme and add that to the css in the module.

**Comment by 73cirdan** [comment]
Hi Martin,

I fixed the css file, added two labels to it in the code, so you can hook up some style elements like color and size.
Also used a bigger font in the code by default.
Lets see if the default works out for you, otherwise just ask for help

Will commit today to master.

**Comment by 73cirdan** [comment]
Ok, the code is up, just do a git clone.  Pay attention to the config.js change. A prefix of MMM- is now needed in the module name: "MMM-rainfc"
Also the git clone command no longer clones to modules/rainfc but to modules/MMM-rainfc

**Comment by martinkooij** [comment]
top, veelbelovend.. Thanks.

. Ik kan de "No Rain Expected" nu niet uitproberen. Maar "No Data" zag er goed leesbaar uit.Dank! 

met MMM-rainfc ipv rainfc is ook alles goedgegaan. 

Ps ik gebruik liever mm/h, dus heb ik de regels voor. "t" te berekenen omgecommentarieerd. 

Cheers,
Martin



⁣Verzonden door Blue ​

Op 27 jan. 2018 18:15, om 18:15, cirdan <notifications@github.com> schreef:

**Comment by 73cirdan** [comment]
mm/h stond nog op mijn todo lijstje, was bang voor grafiekfouten, ziet het er goed uit?

**Comment by martinkooij** [comment]
Ziet er bij ons mooi uit. Heb 'm nu een week, met maximum hoogte op 4. 



⁣Verzonden door Blue ​

Op 27 jan. 2018 18:38, om 18:38, cirdan <notifications@github.com> schreef:
