### ISSUE TITLE
after switch to axios: TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by scientific-method-course** [73cirdan/MMM-rainfc#20]
I just updated to the current version of MMM-rainfc, where the main change seems to be the switch to axios.
This lead the the error TypeError: Cannot read properties of undefined (reading 'get') 

The error seems to be related to the issue quoted here: 
https://forum.magicmirror.builders/topic/13639/axios-request-returns-no-data-while-http-request-does/5

What seemed to solve the problem was to add a line to the first two lines in node_helper.js:

const NodeHelper = require('node_helper');
const axios = require('axios').default;
axios.defaults.headers.common['User-Agent'] = 'PostmanRuntime/7.26.2';

Best, Arnold

**Comment by 73cirdan** [comment]
Thanks for sharing!

I included this fix with an optional parameter in the config, I'm not sure if it introduces errors with other users. 

If you get  the latest version and add the next line to your config in the mmm-rainfc part, it should work

`axiosfix: "PostmanRuntime/7.26.2",`

Could you give it a try ?
If it works, I'll add it to the other modules as well.

**Comment by scientific-method-course** [comment]
Thanks for you quick response. The fix works for me, while this is a clever way to not break things for people that did not have issues.

**Comment by 73cirdan** [comment]
Thanks.

Also changed MMM-bustimes.
(I updated the version of axios also in both modules, may be the fix is not needed with the new version ?)
