### ISSUE TITLE
Error sparkline is not a function

### ISSUE THREAD

**Issue by carstendirks** [73cirdan/MMM-rainfc#6]
I am getting an error in the line `$("#sparkline").sparkline(` that "Uncaught TypeError: $.sparkline is not a function".

I pulled the git repository including the plug-in but somehow it throws this error everytime.

**Comment by 73cirdan** [comment]
Looks like the jquery sparkline lib is not loaded.  

Is the MMM-rainfc module found at: ~/MagicMirror/modules/MMM-rainfc
Is the file jquery.sparkline.min.js in that directory?
Is there one error in the browser log and no modules or does it work and than stops working?

**Comment by carstendirks** [comment]
> Is the MMM-rainfc module found at: ~/MagicMirror/modules/MMM-rainfc
Yes
> Is the file jquery.sparkline.min.js in that directory?
Yes, I also copied the non-min version to it additionally, but did not change a thing

> Is there one error in the browser log and no module shown or does it work and than stops working?
The module itself seems to be working fine, the parsing works, etc. but it fails when using this module all the time.

**Comment by 73cirdan** [comment]
Released version 2 today. 

The module no longer depends on sparkline
