### ISSUE TITLE
Hide module when no rain is forecasted

### ISSUE THREAD

**Issue by Bernard-h** [73cirdan/MMM-rainfc#8]
Hi I love the module. Anyway to hide the module if there is no rain expected? Keeping a clean mirror is important beacause any obsolete info just clogs up the screen. Keeping a magic mirror clean and tidy is important dont you agree?

@73cirdan : Can you provide that? Dat zou top zijn :)

Thank you

**Comment by 73cirdan** [comment]
The module allready autohides the graph when no rain is expected.
I think you also want to remove the header ?
I've  build some code for this and will test it the comming period.

**Comment by 73cirdan** [comment]
Released version 2 today. 

You can use the config: autohide to enable this behavior.
Let me know how this works out for you ?
